2025-05-08 02:03:57,086 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:06:40,314 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:07:07,211 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:11:47,956 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:12:50,437 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:13:27,708 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:13:33,738 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 13:11:46,018 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-08 13:11:46,145 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-08 13:20:54,082 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ~~~~~~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 119, in get_success_url
    if self.success_url:
       ^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'author-works' with no arguments not found. 1 pattern(s) tried: ['works/author_works/(?P<category>[0-9]+)\\Z']
2025-05-08 13:22:11,437 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3
2025-05-08 13:24:47,266 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3/
2025-05-08 13:24:50,229 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3
2025-05-08 13:27:36,158 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3
2025-05-08 13:28:35,063 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/4
2025-05-08 13:29:38,483 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3
2025-05-08 13:33:26,392 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 13:41:14,907 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 16:02:24,501 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-08 16:02:24,519 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-08 16:02:24,656 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-08 16:02:24,662 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-08 16:02:32,785 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/
2025-05-08 18:20:46,561 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-08 18:31:29,060 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 22:25:03,635 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-08 22:25:03,815 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-11 14:38:14,883 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-11 14:38:14,951 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-11 14:39:28,902 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:50:26,960 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:50:57,962 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:52:14,293 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:52:35,574 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:52:40,695 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:53:02,654 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:53:26,895 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:53:29,902 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 14:53:37,890 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:05:48,696 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:06:08,849 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:06:09,602 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:06:22,979 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:07:11,275 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:07:20,493 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:08:38,134 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:09:34,430 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:10:21,317 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:10:29,176 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:10:36,816 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:11:28,905 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:11:39,003 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:11:53,886 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:14:30,657 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:15:04,722 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:15:27,692 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:16:19,881 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:16:32,992 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:17:21,775 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:18:00,084 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:18:14,164 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:18:24,260 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:18:45,668 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:19:12,249 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:19:16,834 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:19:20,479 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:19:21,162 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:20:48,686 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:21:02,320 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:21:12,255 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:21:37,223 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:21:46,129 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:22:08,793 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:23:01,374 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:23:01,994 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:23:02,172 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:23:15,458 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:23:19,964 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:23:36,943 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:29:26,330 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:30:00,553 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:30:12,720 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:30:19,664 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:30:23,799 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:38:07,159 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:38:47,576 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:39:38,814 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:39:46,286 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:39:59,411 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:41:24,890 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:44:32,299 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:46:04,503 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:46:36,046 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:54:45,569 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:55:03,174 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:55:08,709 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:55:14,236 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:55:26,696 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:55:42,861 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:55:50,492 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:56:19,217 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:57:13,129 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 15:58:35,106 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 16:07:53,243 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works
2025-05-11 16:19:44,176 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/14
2025-05-11 16:20:23,577 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 16:20:33,224 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/14
2025-05-11 16:22:03,811 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 16:22:11,707 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/14
2025-05-11 16:33:27,229 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/users/login
2025-05-11 17:11:02,956 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/author_work/16
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 123, in get_context_data
    context['file_name'] = self.object.file.name
                           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Content' object has no attribute 'name'
2025-05-11 17:11:05,115 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/author_work/16
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 123, in get_context_data
    context['file_name'] = self.object.file.name
                           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Content' object has no attribute 'name'
2025-05-11 17:11:15,433 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/author_work/16
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 123, in get_context_data
    context['file_name'] = self.object.file.name
                           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Content' object has no attribute 'name'
2025-05-11 17:51:17,284 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 22:21:57,373 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 22:24:48,588 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-11 22:25:21,115 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-12 11:26:22,036 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-12 11:26:22,152 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-12 11:27:02,566 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-12 11:53:36,117 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/author_works/1
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ~~~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 54, in get_queryset
    kw = self.get_kwargs()
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 83, in get_kwargs
    kwargs = super().kwargs()
             ^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute 'kwargs'. Did you mean: 'args'?
2025-05-12 12:10:21,847 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /common/categories/author-works/
2025-05-12 12:20:52,951 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/author_works
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'categories' not found. 'categories' is not a valid view function or pattern name.
2025-05-12 12:26:02,143 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/author_works
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'categories' not found. 'categories' is not a valid view function or pattern name.
2025-05-12 20:46:43,564 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-12 20:46:43,646 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-13 01:06:34,128 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-13 01:07:43,574 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/verification_code/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 121, in post
    print(page_to_after_confirmation)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-05-13 01:10:46,908 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 62, in post
    print(email, password)
    ~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-05-13 01:11:01,931 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 62, in post
    print(email, password)
    ~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-05-13 01:11:21,868 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ~~~~~~~~~^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\forms.py", line 54, in save
    print(instance)
    ~~~~~^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-05-13 01:13:49,275 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ~~~~~~~~~^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\forms.py", line 54, in save
    print(instance)
    ~~~~~^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-05-13 21:11:04,242 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-14 18:04:36,728 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-14 18:04:36,813 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-14 18:09:43,524 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/author_works/1
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 577, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 1: 'static'. Did you forget to register or load this tag?
2025-05-14 18:11:21,104 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/author_works/1
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 577, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 1: 'static'. Did you forget to register or load this tag?
2025-05-14 16:59:38,349 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:00:52,933 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:03:54,856 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:04:33,171 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:04:47,156 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:04:49,928 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:05:07,600 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:05:19,845 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:08:14,652 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:08:32,263 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-14 17:09:08,228 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:00:21,006 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-15 17:00:21,090 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-15 17:00:37,844 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 134, in form_invalid
    if form.name == "":
       ^^^^^^^^^
AttributeError: 'AuthorWorkForm' object has no attribute 'name'
2025-05-15 17:03:02,381 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 134, in form_invalid
    if form.name == "":
       ^^^^^^^^^
AttributeError: 'AuthorWorkForm' object has no attribute 'name'
2025-05-15 17:03:23,633 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    if form.status == Status.private and form.price == 0:
       ^^^^^^^^^^^
AttributeError: 'AuthorWorkForm' object has no attribute 'status'
2025-05-15 17:21:06,471 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view authors_works.views.view didn't return an HttpResponse object. It returned None instead.
2025-05-15 17:22:06,007 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:23:10,284 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:23:28,751 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:23:31,349 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:24:48,795 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:25:07,915 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:25:07,947 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:25:10,668 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:25:13,309 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:25:39,727 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:25:39,751 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:25:41,408 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:25:49,568 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:26:20,017 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:26:38,659 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:27:25,417 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:27:25,447 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:28:03,039 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 135, in form_invalid
    name = form.cleaned_data['name']
           ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
2025-05-15 17:28:03,078 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:28:43,231 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 138, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:28:43,273 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:38:35,657 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:38:41,020 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 149, in post
    form = self.get_form()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\code\oquArna\oqu-arna-web\authors_works\forms.py", line 14, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
2025-05-15 17:38:41,045 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:38:53,292 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 149, in post
    form = self.get_form()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\code\oquArna\oqu-arna-web\authors_works\forms.py", line 15, in __init__
    self.fields.get('status').initial = Status.public
    ^^^^^^^^^^^
AttributeError: 'AuthorWorkForm' object has no attribute 'fields'
2025-05-15 17:38:53,326 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:39:03,146 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:39:05,914 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:39:06,434 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 17:39:15,952 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/author_work/1
2025-05-15 17:40:21,769 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 138, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 17:41:45,012 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 206, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 201, in errors
    self.full_clean()
    ~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 337, in full_clean
    self._clean_fields()
    ~~~~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 345, in _clean_fields
    self.cleaned_data[name] = field._clean_bound_field(bf)
                              ~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\fields.py", line 272, in _clean_bound_field
    value = bf.initial if self.disabled else bf.data
                                             ^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 225, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChoiceField' object has no attribute 'value_from_datadict'
2025-05-15 17:42:48,337 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 206, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 201, in errors
    self.full_clean()
    ~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 337, in full_clean
    self._clean_fields()
    ~~~~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 345, in _clean_fields
    self.cleaned_data[name] = field._clean_bound_field(bf)
                              ~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\fields.py", line 272, in _clean_bound_field
    value = bf.initial if self.disabled else bf.data
                                             ^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\forms.py", line 225, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChoiceField' object has no attribute 'value_from_datadict'
2025-05-15 17:44:20,600 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 138, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 18:07:29,764 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 18:14:28,407 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 18:14:48,284 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:14:55,476 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:18:03,510 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1081, in render
    return render_value_in_context(output, context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1058, in render_value_in_context
    value = str(value)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\forms\boundfield.py", line 270, in build_widget_attrs
    widget.use_required_attribute(self.initial)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChoiceField' object has no attribute 'use_required_attribute'
2025-05-15 18:23:47,669 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_invalid(form)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\oqu-arna-web\authors_works\views.py", line 136, in form_invalid
    status = form.data['status']
             ~~~~~~~~~^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
2025-05-15 18:26:20,821 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:26:31,986 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:27:01,993 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:35:02,113 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:37:40,303 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:54:48,151 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:54:49,689 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:54:56,245 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/author_work/1
2025-05-15 18:54:56,289 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:55:00,990 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:55:02,755 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:55:04,237 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:55:14,256 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:55:14,855 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:55:15,847 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:55:17,189 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:57:37,486 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:57:42,879 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 18:57:43,352 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 19:06:06,165 [WARNING] django.security.csrf D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Forbidden (CSRF token from POST incorrect.): /works/create_author_work
2025-05-15 19:06:12,876 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works
2025-05-15 19:33:19,338 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 19:43:44,196 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 19:43:45,251 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-15 19:43:46,657 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-16 00:20:51,483 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /users/register_entry_email
2025-05-16 00:20:51,578 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-16 00:20:55,293 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /users/register_entry_email/
2025-05-16 00:21:08,114 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/register_entry_email/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: components/registration_title.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 92, in get
    return render(request, self.template_name)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: components/registration_title.html
2025-05-16 00:21:26,015 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/register_entry_email/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: components/registration_title.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 92, in get
    return render(request, self.template_name)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: components/registration_title.html
2025-05-16 00:21:31,609 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/register_entry_email/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: components/registration_title.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 92, in get
    return render(request, self.template_name)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: components/registration_title.html
2025-05-16 00:21:44,131 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/send_code
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 47, in get
    return redirect('registry-verification-code')
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registry-verification-code' not found. 'registry-verification-code' is not a valid view function or pattern name.
2025-05-16 00:28:55,709 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/send_code
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 47, in get
    return redirect('registry-verification-code')
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registry-verification-code' not found. 'registry-verification-code' is not a valid view function or pattern name.
2025-05-16 00:30:47,921 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/send_code
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 49, in get
    return redirect(after_url)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'verification_code' not found. 'verification_code' is not a valid view function or pattern name.
2025-05-16 00:31:19,871 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/send_code
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 49, in get
    return redirect(after_url)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'verification-code' not found. 'verification-code' is not a valid view function or pattern name.
2025-05-16 00:33:12,531 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/send_code
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 49, in get
    return redirect(after_url)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'verification-code' not found. 'verification-code' is not a valid view function or pattern name.
2025-05-16 00:35:19,278 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 58, in get
    return render(request, 'login.html')
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registry-entry-code' not found. 'registry-entry-code' is not a valid view function or pattern name.
2025-05-16 00:35:35,994 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 58, in get
    return render(request, 'login.html')
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registry-entry-email' not found. 'registry-entry-email' is not a valid view function or pattern name.
2025-05-16 00:35:50,559 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 58, in get
    return render(request, 'login.html')
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registry-entry-email' not found. 'registry-entry-email' is not a valid view function or pattern name.
2025-05-16 00:35:53,891 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 58, in get
    return render(request, 'login.html')
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register-entry-email' not found. 'register-entry-email' is not a valid view function or pattern name.
2025-05-16 00:38:00,619 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/register_verification_code/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 142, in post
    return redirect(page_to_after_confirmation)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register-reset-password' not found. 'register-reset-password' is not a valid view function or pattern name.
2025-05-16 00:40:19,661 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/register_verification_code/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 142, in post
    return redirect(page_to_after_confirmation)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register-reset-password' not found. 'register-reset-password' is not a valid view function or pattern name.
2025-05-16 00:41:45,669 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/register_set_password/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 181, in post
    user.save()
    ^^^^^^^^^
AttributeError: 'HttpResponseRedirect' object has no attribute 'save'
2025-05-16 00:57:45,800 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/register_set_password/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 185, in post
    user.save()
    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2025-05-16 00:58:01,150 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/register_set_password/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 185, in post
    user.save()
    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
2025-05-16 01:08:29,998 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 58, in get
    return render(request, 'login.html')
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'entry-email' not found. 'entry-email' is not a valid view function or pattern name.
2025-05-16 01:09:13,206 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\oqu-arna-web\users\views.py", line 58, in get
    return render(request, 'login.html')
  File "D:\code\oquArna\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'entry-email' not found. 'entry-email' is not a valid view function or pattern name.
2025-05-16 01:27:25,300 [WARNING] django.security.csrf D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Forbidden (CSRF token from POST incorrect.): /users/register_entry_email/
